name: CI
on:
  push:
    branches:
      - '**'
    paths-ignore:
    - 'README.md'
    - '.gitignore'
    - .github/workflows/release.yml

jobs:
  Tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            venv-activate: .venv\Scripts\activate
            name: Windows
          - os: ubuntu-latest
            venv-activate: source .venv/bin/activate
            name: Linux

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install virtualenv
        run: |
          python -m venv .venv
          ${{ matrix.venv-activate }}
          pip install -r requirements.txt

      - name: Run unittest
        run: |
          ${{ matrix.venv-activate }}
          python -m unittest discover -p *_test.py