name: CI
on:
  push:
    branches:
      - '**'
    paths-ignore:
    - 'README.md'
    - '.gitignore'
    - .github/workflows/release.yml


jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install virtualenv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run unittest
        run: |
          source .venv/bin/activate
          python -m unittest discover -p *_test.py

  tests-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install virtualenv
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          pip install -r requirements.txt

      - name: Run unittest
        run: |
          .venv\Scripts\activate
          python -m unittest discover -p *_test.py
